### ISSUE TITLE
crash on upload

### ISSUE THREAD

**Issue by zkrige** [shr3jn/fastlane-plugin-huawei_appgallery_connect#23] opened 2021-03-03 10:42 UTC
```
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
NoMethodError: [!] undefined method `[]' for nil:NilClass
  /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-huawei_appgallery_connect-1.0.15/lib/fastlane/plugin/huawei_appgallery_connect/helper/huawei_appgallery_connect_helper.rb:151:in `upload_app'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-huawei_appgallery_connect-1.0.15/lib/fastlane/plugin/huawei_appgallery_connect/actions/huawei_appgallery_connect_action.rb:18:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
```

**Comment by zkrige** [comment] 2021-04-27 05:14
@shr3jn is there a possibility you can take a look at this

**Comment by shr3jn** [comment] 2021-04-27 05:16
ok will check this!!

**Comment by shr3jn** [comment] 2021-04-27 05:16
can you post your FastFile?

**Comment by zkrige** [comment] 2021-04-27 05:18
```
lane :huawei do
        gradle(
            task: "bundleThemeReaderBook"
        )
        AAB_LOCATION = "#{lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]}"
        huawei_appgallery_connect(
            client_id: "<redacted>",
            client_secret: "<redacted>",
            app_id: "<redacted>",
            apk_path: AAB_LOCATION,


            # Optional, Parameter beyond this are optional
            #submit_for_review: false,
            #privacy_policy_url: "https://example.com",
            #changelog_path: "<PATH_TO_CHANGELOG_FILE>",

            # release time to release app on specific date
            #release_time: "2019-12-25T07:05:15+0000",

            # For phase wise release: set these parameters
            #phase_wise_release: true,
            #phase_release_start_time: "2019-12-25T07:05:15+0000",
            #phase_release_end_time: "2019-12-28T07:05:15+0000",
            #phase_release_percent: "10.00",
            #phase_release_description: "<DESCRIPTION>"
        )
    end
    ```

**Comment by shr3jn** [comment] 2021-04-30 12:47
have u tried locally by giving a direct file path ?

**Comment by zkrige** [comment] 2021-05-03 13:32
This was working fine, but it stopped working. Do you think its maybe the file path? FWIW, this file path works for other lanes

**Comment by shr3jn** [comment] 2021-12-10 08:43
not able to reproduce issue. closing for now.

**Closed by shr3jn** 2021-12-10 08:43 UTC
